# Generated by Django 5.0.1 on 2024-04-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wind",
                    models.DecimalField(decimal_places=5, default=0, max_digits=25),
                ),
                (
                    "pressure",
                    models.DecimalField(decimal_places=2, default=0, max_digits=25),
                ),
                ("name", models.CharField(default=None, max_length=100)),
                ("category", models.CharField(default=None, max_length=50)),
                (
                    "original_img",
                    models.ImageField(default="image.jpg", upload_to="archive/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
